sonar.projectKey=recordatorin
sonar.projectName=Recordatorin
sonar.sources=src,electron
sonar.tests=src,electron
sonar.exclusions=node_modules/**,out/**,dist/**,release/**,coverage/**
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
